amcl:
  ros__parameters:
    use_sim_time: True
    
    # Frames
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"
    
    # Particle Filter Parameters
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.1 
    update_min_a: 0.2  
    resample_interval: 1
    
    
    odom_model_type: diff
    odom_alpha1: 0.2   # Rotation noise from rotation
    odom_alpha2: 0.2   # Rotation noise from translation
    odom_alpha3: 0.8   # Translation noise from translation
    odom_alpha4: 0.2   # Translation noise from rotation
    odom_alpha5: 0.1   # Translation from rotation (for non-holonomic robots)
    
    # Laser model parameters
    laser_model_type: likelihood_field
    # Laser scan topic (converted from point cloud)
    scan_topic: scan
    
    laser_max_range: -1.0  
    laser_max_beams: 60
    laser_z_hit: 0.5
    laser_z_short: 0.05
    laser_z_max: 0.05
    laser_z_rand: 0.5
    laser_sigma_hit: 0.2
    laser_lambda_short: 0.1
    laser_likelihood_max_dist: 2.0

    # TF publication
    tf_broadcast: True

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "depot.yaml"
    topic_name: "map"
    frame_id: "map"